Website/Code/Inventory/Inventory/Controllers/MaintenanceController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inventory.Utils;
using Inventory.Security;
using Inventory.Models;
using Inventory.DataLayer.Repository;

namespace Inventory.Controllers
{
    [Authorize]
    public class MaintenanceController : Controller
    {
        
        public ActionResult Shippers()
        {
            List<Shipper> shippers = new List<Shipper>();
            using (MySqlConnection conn = DBUtils.GetConnection()) {
                ShipperRepository repo = new ShipperRepository(conn);
                shippers = repo.GetAll().ToList<Shipper>();
            }
            return View(shippers);
        }
        
        public ActionResult PartialShippers()
        {
            List<Shipper> shippers = new List<Shipper>();
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                ShipperRepository repo = new ShipperRepository(conn);
                shippers = repo.GetAll().ToList<Shipper>();
            }
            return PartialView("Shippers", shippers);
        }

        public ActionResult Shipper(Int32 id) {
            Shipper shipper;
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                ShipperRepository repo = new ShipperRepository(conn);
                shipper = repo.GetById(id.ToString());
            }

            return View(shipper);
        }

        [HttpPost]
        public ActionResult Shipper(Shipper ship)
        {
            if (ModelState.IsValid)
            {
                using (MySqlConnection conn = DBUtils.GetConnection())
                {
                    ShipperRepository repo = new ShipperRepository(conn);
                    repo.Save(ship);
                }

                return RedirectToAction("Shippers");
            }
            return View(ship);
        }

        public ActionResult CreateShipper()
        {
            Shipper ship = new Shipper();

            return View(ship);
        }

        [HttpPost]
        public ActionResult CreateShipper(Shipper ship)
        {
            if (ModelState.IsValid)
            {
                using (MySqlConnection conn = DBUtils.GetConnection())
                {
                    ShipperRepository repo = new ShipperRepository(conn);
                    repo.Save(ship);
                }

                return RedirectToAction("Shippers");
            }
            return View(ship);
        }

        public ActionResult Suppliers()
        {
            List<Supplier> suppliers = new List<Supplier>();
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                SupplierRepository repo = new SupplierRepository(conn);
                suppliers = repo.GetAll().ToList<Supplier>();
            }
            return View(suppliers);
        }

        public ActionResult Supplier(Int32 id)
        {
            Supplier supplier;
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                SupplierRepository repo = new SupplierRepository(conn);
                supplier = repo.GetById(id.ToString());
            }

            return View(supplier);
        }

        public ActionResult Customers()
        {
            List<Customer> customers = new List<Customer>();
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                CustomerRepository repo = new CustomerRepository(conn);
                customers = repo.GetAll().ToList<Customer>();
            }
            return View(customers);
        }

        public ActionResult Customer(string id)
        {
            Customer customer;
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                CustomerRepository repo = new CustomerRepository(conn);
                customer = repo.GetById(id);
            }

            return View(customer);
        }

        public ActionResult Products()
        {
            List<Product> products = new List<Product>();
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                ProductRepository repo = new ProductRepository(conn);
                products = repo.GetAll().ToList<Product>();
            }
            return View(products);
        }

        public ActionResult Product(Int32 id)
        {
            Product product;
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                ProductRepository repo = new ProductRepository(conn);
                product = repo.GetById(id.ToString());
            }

            EditProduct prod = new EditProduct();
            prod.ProductID = product.ProductID;
            prod.ProductName = product.ProductName;
            prod.UnitsInStock = product.UnitsInStock;
            prod.UnitsOnOrder = product.UnitsOnOrder;
            prod.ActiveYN = product.ActiveYN;

            return View(prod);
        }

        [HttpPost]
        public ActionResult Product(EditProduct prod)
        {
            if (ModelState.IsValid)
            {
                using (MySqlConnection conn = DBUtils.GetConnection())
                {
                    Product product = new Product();

                    product.ProductID = prod.ProductID;
                    product.ProductName = prod.ProductName;
                    product.UnitsInStock = prod.UnitsInStock;
                    product.UnitsOnOrder = prod.UnitsOnOrder;
                    product.ActiveYN = prod.ActiveYN;

                    ProductRepository repo = new ProductRepository(conn);
                    repo.Save(product);
                }

                return RedirectToAction("Products");
            }

            return View(prod);
        }
    }
}

Website/Code/Inventory/Inventory/Controllers/OrderController.cs
using Inventory.DataLayer.Repository;
using Inventory.Models;
using Inventory.Utils;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventory.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            List<DisplayOrder> orders = new List<DisplayOrder>();
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                DisplayOrderHistoryRepository repo = new DisplayOrderHistoryRepository(conn);
                orders = repo.GetAll().ToList<DisplayOrder>();
            }
            return View(orders);
        }

        [HttpPost]
        public ActionResult Index(string searchString)
        {
            List<DisplayOrder> orders = new List<DisplayOrder>();
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                DisplayOrderHistoryRepository repo = new DisplayOrderHistoryRepository(conn);
                orders = repo.GetByQuery(searchString).ToList<DisplayOrder>();
            }
            return PartialView("Orders", orders);
        }

        // GET: Order/Details/5
        public ActionResult Details(int id)
        {
            Orders order;
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                OrderRepository repo = new OrderRepository(conn);
                order = repo.GetById(id);
            }

            return View(order);
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            CreateOrder order = new CreateOrder();

            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                DisplayCustomerRepository cust = new DisplayCustomerRepository(conn);
                order.CustomerList = cust.GetAll().ToList<DisplayCustomer>();

                DisplayShipperRepository shipper = new DisplayShipperRepository(conn);
                order.ShipperList = shipper.GetAll().ToList<DisplayShipper>();

                //DisplayProductRepository product = new DisplayProductRepository(conn);
                //order.ProductList = product.GetAll().ToList<DisplayProduct>();

            }

            return View(order);
        }

        // POST: Order/Create
        [HttpPost]
        public ActionResult Create(CreateOrder order)
        {

            if (ModelState.IsValid)
            {
                Orders newOrder = new Orders();
                Int32 newOrderID = 0;
                using (MySqlConnection conn = DBUtils.GetConnection())
                {
                    CustomerRepository custRepo = new CustomerRepository(conn);
                    Customer cust = custRepo.GetById(order.CustomerID);
                    Users user = (Users)Session["User"];


                    newOrder.CustomerID = order.CustomerID;
                    newOrder.ShipperID = order.ShipperID;
                    newOrder.OrderDate = order.OrderDate;
                    newOrder.RequiredDate = order.RequiredDate;
                    newOrder.Freight = order.Freight;
                    newOrder.UserID = user.UserID;

                    newOrder.ShippedName = cust.CompanyName;
                    newOrder.ShippedAddress = cust.Address;
                    newOrder.ShippedCity = cust.City;
                    newOrder.ShippedRegion = cust.Region;
                    newOrder.ShippedPostalCode = cust.PostalCode;
                    newOrder.ShippedCountry = cust.Country;

                    OrderRepository orderRepo = new OrderRepository(conn);
                    newOrderID = orderRepo.Save(newOrder);
                }

                return RedirectToAction("Details", new { id = newOrderID });
            }

            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                DisplayCustomerRepository cust = new DisplayCustomerRepository(conn);
                order.CustomerList = cust.GetAll().ToList<DisplayCustomer>();

                DisplayShipperRepository shipper = new DisplayShipperRepository(conn);
                order.ShipperList = shipper.GetAll().ToList<DisplayShipper>();

                //DisplayProductRepository product = new DisplayProductRepository(conn);
                //order.ProductList = product.GetAll().ToList<DisplayProduct>();

            }

            return View("Create", order);

        }

        public ActionResult ShipOrder(int id)
        {
            Orders order;
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                OrderRepository repo = new OrderRepository(conn);
                order = repo.GetById(id);

            }

            EditOrder ship = new EditOrder();
            ship.OrderID = order.OrderID;
            ship.OrderDate = order.OrderDate;
            ship.RequiredDate = order.RequiredDate;
            ship.ShippedName = order.ShippedName;
            return View(ship);
        }

        [HttpPost]
        public ActionResult ShipOrder(EditOrder ship)
        {
            if (ModelState.IsValid)
            {
                using (MySqlConnection conn = DBUtils.GetConnection())
                {
                    Orders order = new Orders();

                    order.OrderID = ship.OrderID;
                    order.ShippedDate = ship.ShippedDate;

                    OrderRepository repo = new OrderRepository(conn);
                    repo.Save(order);
                }

                return RedirectToAction("Index");
            }

            return View(ship);
        }
        
        public ActionResult DeleteOrder(int orderId)
        {
            try
            {
                // TODO: Add delete logic here
                using (MySqlConnection conn = DBUtils.GetConnection())
                {
                    OrderRepository orderRepo = new OrderRepository(conn);
                    orderRepo.Delete(orderId);
                }               

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult OrderDetails(int id)
        {
            List<OrderDetails> orderdet;
            DisplayOrderDetails displayDet = new DisplayOrderDetails();
            displayDet.OrderID = id;

            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                OrderDetailsRepository repo = new OrderDetailsRepository(conn);
                orderdet = repo.GetById(id).ToList<OrderDetails>();
            }

            displayDet.Details = orderdet;
            return View(displayDet);
        }

        // GET: Order/Create
        public ActionResult CreateOrderDetail(int id)
        {
            CreateOrderDetail order = new CreateOrderDetail();
            order.OrderID = id;
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                DisplayProductRepository product = new DisplayProductRepository(conn);
                order.ProductList = product.GetAll().ToList<DisplayProduct>();

            }

            return View(order);
        }

        // POST: Order/Create
        [HttpPost]
        public ActionResult CreateOrderDetail(int id, CreateOrderDetail orderDetail)
        {
            if (ModelState.IsValid)
            {
                using (MySqlConnection conn = DBUtils.GetConnection())
                {
                    OrderDetails orderdet = new OrderDetails();

                    orderdet.OrderID = orderDetail.OrderID;
                    orderdet.ProductID = orderDetail.ProductID;
                    orderdet.Quantity = orderDetail.Quantity;
                    orderdet.UnitPrice = orderDetail.UnitPrice;
                    orderdet.Discount = 0;
                    
                    OrderDetailsRepository orderRepo = new OrderDetailsRepository(conn);
                    orderRepo.Save(orderdet);
                }

                return RedirectToAction("OrderDetails", new { id = orderDetail.OrderID });
            }

            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                DisplayProductRepository product = new DisplayProductRepository(conn);
                orderDetail.ProductList = product.GetAll().ToList<DisplayProduct>();

            }

            return View(orderDetail);
        }
              
        public ActionResult DeleteOrderDetails(int orderId, int productId)
        {
            try
            {
                // TODO: Add delete logic here
                using (MySqlConnection conn = DBUtils.GetConnection())
                {
                    OrderDetailsRepository orderRepo = new OrderDetailsRepository(conn);
                    orderRepo.Delete(orderId, productId);
                }

                return RedirectToAction("OrderDetails", new { id = orderId });
                
            }
            catch
            {
                return RedirectToAction("OrderDetails", new { id = orderId });
            }
        }
    }
}

Website/Code/Inventory/Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    <style type="text/css">
        .search-container {
            float: left;
        }

            .search-container button {
                float: right;
                padding: 6px 10px;
                margin-right: 16px;
                background: #ddd;
                border: none;
                cursor: pointer;
            }

                .search-container button:hover {
                    background: #ccc;
                }

            .search-container input[type=text] {
                padding: 6px;
                border: none;
            }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
        <a class="navbar-brand" href="#">Inventory Management System</a>&nbsp;&nbsp;Welcome
        @{Inventory.Models.Users usr = (Inventory.Models.Users)Session["User"]; }
        @usr.UserName.ToUpper()
        <div>
            <div class="search-container">
                <form method="post" action="@Url.Action("Search", "Home")">
                    <input type="text" placeholder="Search.." name="searchString">
                    <button type="submit"><i class="fa fa-search"></i></button>
                </form>
            </div>
            &nbsp;&nbsp;
            <a href="#" onclick="location.href='@Url.Action("Logout", "Account")'"><i class="fa fa-power-off fa-2x"></i></a>
        </div>
    </nav>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-2">
                <a class="btn" href="#" onclick="location.href='@Url.Action("Index", "Home")'" role="button">
                    <i class="fa fa-home fa-2x"></i>
                </a>
                <ul class="nav flex-column">
                    @if (usr.RoleID == 1)
                    {
                        <li class="nav-item">
                            <a class="nav-link active" href="#" onclick="location.href='@Url.Action("Administrator", "Administrators")'" role="button">Administration</a>
                        </li>
                    }
                    @if (usr.RoleID == 1 || usr.RoleID == 2)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Maintenance</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#" onclick="location.href='@Url.Action("Shippers", "Maintenance")'">Shipper</a>
                                <a class="dropdown-item" href="#" onclick="location.href='@Url.Action("Suppliers", "Maintenance")'">Supplier</a>
                                <a class="dropdown-item" href="#" onclick="location.href='@Url.Action("Customers", "Maintenance")'">Customer</a>
                                <a class="dropdown-item" href="#" onclick="location.href='@Url.Action("Products", "Maintenance")'">Product</a>
                            </div>
                        </li>
                    }
                    <li class="nav-item dropdown">
                        <a class="nav-link active" href="#" onclick="location.href='@Url.Action("Index", "Order")'">Order</a>
                    </li>
                </ul>

            </div>
            <div class="col-md-10">
                <form>
                    @RenderBody()
                </form>
            </div>
        </div>
        <hr />
        <footer>
            <p>&copy;2018 - Senior Project Fall</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $('.tree-toggle').click(function () {
            $(this).parent().children('ul.tree').toggle(200);
        });
        $(function () {
            $('.tree-toggle').parent().children('ul.tree').toggle();
        })
    </script>
</body>
</html>

Website/Code/Inventory/Inventory/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <form>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Inventory Management System</a>
        </nav>

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy;2018 - Senior Project Fall</p>
            </footer>
        </div>
    </form>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>