Website/Code/Inventory/Inventory/Models/Administrators.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Inventory.Models
{
    public class Administrators
    {
        [Display(Name = "User Name"), Required(ErrorMessage = "Please enter User Name")]
        public String UserName { get; set; }
        [Display(Name = "User Role")]
        public String User_Type { get; set; }
    }
}

Website/Code/Inventory/Inventory/Models/Users.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;


namespace Inventory.Models
{
    public class Users
    {
        [ScaffoldColumn(false)]
        public Int32 UserID { get; set; }
        [Display(Name = "User Name"), Required(ErrorMessage = "Please enter User Name")]
        public String UserName { get; set; }
        [Display(Name = "Password"), Required(ErrorMessage = "Please enter Password"), DataType(DataType.Password)]
        public String Password { get; set; }
        [Display(Name = "Re-Enter Password"), Required(ErrorMessage = "Please re-enter Password"), DataType(DataType.Password)]
        public String Password1 { get; set; }
        [Display(Name = "First Name"), Required(ErrorMessage = "Please enter First Name")]
        public String FirstName { get; set; }
        [Display(Name = "Last Name"), Required(ErrorMessage = "Please enter Last Name")]
        public String LastName { get; set; }
        [Display(Name = "Phone Number"), Required(ErrorMessage = "Please enter Phone Number")]
        public String PhoneNumber { get; set; }
        [Display(Name = "Street"), Required(ErrorMessage = "Please enter Street")]
        public String Street { get; set; }
        [Display(Name = "City"), Required(ErrorMessage = "Please enter City")]
        public String City { get; set; }
        [Display(Name = "Zip Code"), Required(ErrorMessage = "Please enter Zip Code")]
        public String ZipCode { get; set; }
        [Display(Name = "Email"), Required(ErrorMessage = "Please enter Email")]
        public String Email { get; set; }
        [Display(Name = "Role Id")]
        public Int16 RoleID { get; set; }
        public String ActiveYN { get; set; }

    }

    public class DisplayUsers
    {
        [ScaffoldColumn(false)]
        public int UserID { get; set; }
        [DisplayName("Shipper")]
        public string UserName { get; set; }
    }
}

Website/Code/Inventory/Inventory/Controllers/AdministratorsController.cs
using Inventory.DataLayer.Repository;
using Inventory.Models;
using Inventory.Security;
using Inventory.Utils;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventory.Controllers
{
    [Authorize]
    public class AdministratorsController : Controller
    {
        SessionContext context = new SessionContext();

        public ActionResult Administrator()
        {
            return View();
        }

        public ActionResult Edit(Int32 userID)
        {
            Users users = null;
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                UsersRepository repo = new UsersRepository(conn);
                users = repo.GetById(userID.ToString());
            }
            if (users != null)
            {
                Administrators admin = new Administrators();
                admin.UserName = users.UserName;
                switch (users.RoleID)
                {
                    case 1:
                        admin.User_Type = "Administrator";
                        break;
                    case 2:
                        admin.User_Type = "Manager";
                        break;
                    case 3:
                        admin.User_Type = "Cashier";
                        break;
                }
                return View("Administrator", admin);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult EditUser(Users user)
        {
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                UsersRepository repo = new UsersRepository(conn);
                    Dictionary<String, Object> hash = new Dictionary<String, Object>();
                    hash.Add("UserName", user.UserName);
                    hash.Add("Password", user.Password);
                    hash.Add("FirstName", user.FirstName);
                    hash.Add("LastName", user.LastName);
                    hash.Add("PhoneNumber", user.PhoneNumber);
                    hash.Add("Street", user.Street);
                    hash.Add("City", user.City);
                    hash.Add("ZipCode", user.ZipCode);
                    hash.Add("Email", user.Email);
                    hash.Add("UserID", user.UserID);
                    repo.SetAll(hash);
            }
            return RedirectToAction("Administrator", new Administrators());
        }

        public ActionResult DeleteUser(Int32 userId)
        {
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                UsersRepository repo = new UsersRepository(conn);
                repo.SetInactive(userId.ToString());
            }
            return RedirectToAction("Administrator", new Administrators());
        }

        public ActionResult ViewDetails(Int32 userID)
        {
            Users users = null;
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                UsersRepository repo = new UsersRepository(conn);
                users = repo.GetById(userID.ToString());
            }
            if (users != null)
            {
                return PartialView("UserDetails", users);
            }
            else
                return RedirectToAction("Administrator", new Administrators());
        }

        public ActionResult ChangeUsers()
        {
            List<Users> users = new List<Users>();
            using (MySqlConnection conn = DBUtils.GetConnection())
            {
                UsersRepository repo = new UsersRepository(conn);
                users = repo.GetAll().ToList<Users>();
            }
            return PartialView("Users", users);
        }

        [HttpPost]
        public ActionResult ChangeRole(Administrators admin)
        {
            if (admin.UserName != null)
            {
                using (MySqlConnection conn = DBUtils.GetConnection())
                {
                    UsersRepository repo = new UsersRepository(conn);
                    Users user = repo.GetByName(admin.UserName);
                    if (user != null) {
                        switch (admin.User_Type) {
                            case "Administrator":
                                repo.changeUserRole(admin.UserName, "1");
                                break;
                            case "Manager":
                                repo.changeUserRole(admin.UserName, "2");
                                break;
                            case "Cashier":
                                repo.changeUserRole(admin.UserName, "3");
                                break;
                        }
                    }
                }
            }
            return View("Administrator");
        }
    }
}

Website/Code/Inventory/Inventory/Views/Administrators/Administrator.cshtml
@model Inventory.Models.Administrators

@{
    ViewBag.Title = "Administrator";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Administration</h1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        @Html.Action("ChangeUsers", "Administrators")
    </div>
    <br />
    <h4>Change User Roles</h4>
    <hr />
    <div class="row">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.UserName, new { MaxLength = 20, Length = 20})
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        @Html.LabelFor(model => model.User_Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @{
                List<SelectListItem> listItems = new List<SelectListItem>();
                listItems.Add(new SelectListItem
                {
                    Text = "Administrator",
                    Value = "Administrator"
                });
                listItems.Add(new SelectListItem
                {
                    Text = "Manager",
                    Value = "Manager"
                });
                listItems.Add(new SelectListItem
                {
                    Text = "Cashier",
                    Value = "Cashier"
                });
            }
            @Html.DropDownListFor(model => model.User_Type, listItems, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.User_Type, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-2 col-md-2">
            <input type="submit" value="Submit" class="btn btn-default" formaction=@Url.Action("ChangeRole") formmethod="post" />
        </div>
    </div>
    <br />
</div>
    
}

Website/Code/Inventory/Inventory/Views/Administrators/UserDetails.cshtml
@model Inventory.Models.Users
@{
    ViewBag.Title = "UserDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h5>UserDetails</h5>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <table class="table">
        <tr>
            <th>
                <Label>User</Label>
            </th>
            <th>
                <Label>Action</Label>
            </th>
            <th></th>

        </tr>
        <tr>
            <td>
                <div class="row">
                    <div class="col-md-2">
                        <label>First Name</label>
                    </div>
                    <div class="col-md-2">
                        @Html.TextBoxFor(m => m.FirstName, new { MaxLength = 25 })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <label>Last Name</label>
                    </div>
                    <div class="col-md-2">
                        @Html.TextBoxFor(m => m.LastName, new { MaxLength = 25 })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <label>Phone</label>
                    </div>
                    <div class="col-md-2">
                        @Html.TextBoxFor(m => m.PhoneNumber, new { MaxLength = 10 })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <label>Street</label>
                    </div>
                    <div class="col-md-2">
                        @Html.TextBoxFor(m => m.Street, new { MaxLength = 25 })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <label>City</label>
                    </div>
                    <div class="col-md-2">
                        @Html.TextBoxFor(m => m.City, new { MaxLength = 25 })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <label>Zip Code</label>
                    </div>
                    <div class="col-md-2">
                        @Html.TextBoxFor(m => m.ZipCode, new { MaxLength = 5 })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <label>Email</label>
                    </div>
                    <div class="col-md-2">
                        @Html.TextBoxFor(m => m.Email, new { MaxLength = 40 })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        @Html.TextBoxFor(m => m.RoleID, new { style = "display: none;" })
                        @Html.TextBoxFor(m => m.UserID, new { style = "display: none;" })
                        @Html.TextBoxFor(m => m.UserName, new { style = "display: none;" })
                        @Html.TextBoxFor(m => m.ActiveYN, new { style = "display: none;" })
                    </div>
                   
            </td>
            <td>
                <input type="submit" value="Save" class=" btn-default" formaction=@Url.Action("EditUser") formmethod="post" />
                <hr />
                @Html.ActionLink("Delete", "DeleteUser", "Administrators", new { Model.UserID }, "")
            </td>
            
        </tr>

    </table>
    <br/>
    <hr/>
    <div>
        @Html.ActionLink("Back to Administration", "Administrator", "Administrators")
    </div>
 }

Website/Code/Inventory/Inventory/Views/Administrators/Users.cshtml
@model IEnumerable<Inventory.Models.Users>

<h4>Users</h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleID)
        </th>
        <th></th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @{ 
                    if (item.RoleID.Equals(1))
                    {
                        <label>Administrator</label>
                    }
                    else if (item.RoleID.Equals(2))
                    {
                        <label>Manager</label>
                    }
                    else if (item.RoleID.Equals(3))
                    {
                        <label>Cashier</label>
                    }
            }
            </td>
                    <td>
                        @Html.ActionLink("Change Role", "Edit", "Administrators", new { item.UserID }, "")
                        <hr/>
                        @Html.ActionLink("Edit", "ViewDetails", "Administrators", new { item.UserID}, "")
                    </td>
                </tr>
    }
</table>